<?php
/**
 * Dados iniciais do cronograma (seed).
 * Gerado a partir do escopo do projeto. Edite aqui se o escopo mudar,
 * ou use o painel administrativo para atualizar apenas o status das tarefas.
 */

return [
    ['module' => 'Módulo 1 – Diagnóstico e Correção do Site', 'module_short' => 'M1', 'module_order' => 1, 'task_num' => '1.1', 'task_name' => 'Levantamento técnico completo da plataforma Webstore', 'responsible' => 'Time Técnico', 'duration' => 2, 'start_date' => '2026-07-13', 'end_date' => '2026-07-14', 'module_investment' => 1200.00],
    ['module' => 'Módulo 1 – Diagnóstico e Correção do Site', 'module_short' => 'M1', 'module_order' => 1, 'task_num' => '1.2', 'task_name' => 'Correção das variáveis dinâmicas quebradas ({{value}})', 'responsible' => 'Time Técnico', 'duration' => 2, 'start_date' => '2026-07-15', 'end_date' => '2026-07-16', 'module_investment' => 1200.00],
    ['module' => 'Módulo 1 – Diagnóstico e Correção do Site', 'module_short' => 'M1', 'module_order' => 1, 'task_num' => '1.3', 'task_name' => 'Configuração de checkout, pagamento e selos de segurança', 'responsible' => 'Time Técnico', 'duration' => 2, 'start_date' => '2026-07-17', 'end_date' => '2026-07-20', 'module_investment' => 1200.00],
    ['module' => 'Módulo 1 – Diagnóstico e Correção do Site', 'module_short' => 'M1', 'module_order' => 1, 'task_num' => '1.4', 'task_name' => 'Otimização mobile-first e velocidade de carregamento', 'responsible' => 'Time Técnico', 'duration' => 2, 'start_date' => '2026-07-21', 'end_date' => '2026-07-22', 'module_investment' => 1200.00],
    ['module' => 'Módulo 1 – Diagnóstico e Correção do Site', 'module_short' => 'M1', 'module_order' => 1, 'task_num' => '1.5', 'task_name' => 'Verificação/ajuste integração Webstore ↔ Bling ERP', 'responsible' => 'Time Técnico', 'duration' => 1, 'start_date' => '2026-07-23', 'end_date' => '2026-07-23', 'module_investment' => 1200.00],
    ['module' => 'Módulo 1 – Diagnóstico e Correção do Site', 'module_short' => 'M1', 'module_order' => 1, 'task_num' => '1.6', 'task_name' => 'Teste end-to-end do fluxo de venda', 'responsible' => 'Time Técnico', 'duration' => 1, 'start_date' => '2026-07-24', 'end_date' => '2026-07-24', 'module_investment' => 1200.00],
    ['module' => 'Módulo 3 – Identidade Visual, Posicionamento e Presença Local', 'module_short' => 'M3', 'module_order' => 3, 'task_num' => '3.1', 'task_name' => 'Refinamento do manual de marca (cores, tipografia, tom de voz)', 'responsible' => 'Time Marketing/Branding', 'duration' => 3, 'start_date' => '2026-07-13', 'end_date' => '2026-07-15', 'module_investment' => 1500.00],
    ['module' => 'Módulo 3 – Identidade Visual, Posicionamento e Presença Local', 'module_short' => 'M3', 'module_order' => 3, 'task_num' => '3.2', 'task_name' => 'Definição do posicionamento estratégico da marca', 'responsible' => 'Time Marketing/Branding', 'duration' => 3, 'start_date' => '2026-07-16', 'end_date' => '2026-07-20', 'module_investment' => 1500.00],
    ['module' => 'Módulo 3 – Identidade Visual, Posicionamento e Presença Local', 'module_short' => 'M3', 'module_order' => 3, 'task_num' => '3.3', 'task_name' => 'Criação e configuração completa do Google Meu Negócio', 'responsible' => 'Time Marketing/Branding', 'duration' => 3, 'start_date' => '2026-07-21', 'end_date' => '2026-07-23', 'module_investment' => 1500.00],
    ['module' => 'Módulo 3 – Identidade Visual, Posicionamento e Presença Local', 'module_short' => 'M3', 'module_order' => 3, 'task_num' => '3.4', 'task_name' => 'Otimização do perfil GMB (categorias, descrição, horários, fotos, produtos)', 'responsible' => 'Time Marketing/Branding', 'duration' => 2, 'start_date' => '2026-07-24', 'end_date' => '2026-07-27', 'module_investment' => 1500.00],
    ['module' => 'Módulo 3 – Identidade Visual, Posicionamento e Presença Local', 'module_short' => 'M3', 'module_order' => 3, 'task_num' => '3.5', 'task_name' => 'Estratégia de captação de avaliações e respostas', 'responsible' => 'Time Marketing/Branding', 'duration' => 2, 'start_date' => '2026-07-28', 'end_date' => '2026-07-29', 'module_investment' => 1500.00],
    ['module' => 'Módulo 3 – Identidade Visual, Posicionamento e Presença Local', 'module_short' => 'M3', 'module_order' => 3, 'task_num' => '3.6', 'task_name' => 'Integração GMB com GA4 e Search Console', 'responsible' => 'Time Marketing/Branding', 'duration' => 2, 'start_date' => '2026-07-30', 'end_date' => '2026-07-31', 'module_investment' => 1500.00],
    ['module' => 'Módulo 2 – Instalação de Rastreamento', 'module_short' => 'M2', 'module_order' => 2, 'task_num' => '2.1', 'task_name' => 'Meta Pixel + Conversions API', 'responsible' => 'Time Tracking/Dados', 'duration' => 2, 'start_date' => '2026-07-20', 'end_date' => '2026-07-21', 'module_investment' => 800.00],
    ['module' => 'Módulo 2 – Instalação de Rastreamento', 'module_short' => 'M2', 'module_order' => 2, 'task_num' => '2.2', 'task_name' => 'Google Tag Manager configurado', 'responsible' => 'Time Tracking/Dados', 'duration' => 2, 'start_date' => '2026-07-22', 'end_date' => '2026-07-23', 'module_investment' => 800.00],
    ['module' => 'Módulo 2 – Instalação de Rastreamento', 'module_short' => 'M2', 'module_order' => 2, 'task_num' => '2.3', 'task_name' => 'Google Analytics 4 com eventos de conversão mapeados', 'responsible' => 'Time Tracking/Dados', 'duration' => 2, 'start_date' => '2026-07-24', 'end_date' => '2026-07-27', 'module_investment' => 800.00],
    ['module' => 'Módulo 2 – Instalação de Rastreamento', 'module_short' => 'M2', 'module_order' => 2, 'task_num' => '2.4', 'task_name' => 'Google Merchant Center + feed de produtos (sincronizado via Bling)', 'responsible' => 'Time Tracking/Dados', 'duration' => 2, 'start_date' => '2026-07-28', 'end_date' => '2026-07-29', 'module_investment' => 800.00],
    ['module' => 'Módulo 2 – Instalação de Rastreamento', 'module_short' => 'M2', 'module_order' => 2, 'task_num' => '2.5', 'task_name' => 'Relatórios de origem de vendas integrados ao Bling', 'responsible' => 'Time Tracking/Dados', 'duration' => 2, 'start_date' => '2026-07-30', 'end_date' => '2026-07-31', 'module_investment' => 800.00],
    ['module' => 'Módulo 4 – Estruturação dos Marketplaces e Integração Bling', 'module_short' => 'M4', 'module_order' => 4, 'task_num' => '4.1', 'task_name' => 'Mercado Livre: criação e configuração da conta vendedor', 'responsible' => 'Time Marketplaces', 'duration' => 2, 'start_date' => '2026-07-27', 'end_date' => '2026-07-28', 'module_investment' => 1600.00],
    ['module' => 'Módulo 4 – Estruturação dos Marketplaces e Integração Bling', 'module_short' => 'M4', 'module_order' => 4, 'task_num' => '4.2', 'task_name' => 'Configuração do perfil de vendedor (reputação, políticas, dados)', 'responsible' => 'Time Marketplaces', 'duration' => 1, 'start_date' => '2026-07-29', 'end_date' => '2026-07-29', 'module_investment' => 1600.00],
    ['module' => 'Módulo 4 – Estruturação dos Marketplaces e Integração Bling', 'module_short' => 'M4', 'module_order' => 4, 'task_num' => '4.3', 'task_name' => 'Inserção e otimização de até 30 produtos', 'responsible' => 'Time Marketplaces', 'duration' => 4, 'start_date' => '2026-07-30', 'end_date' => '2026-08-04', 'module_investment' => 1600.00],
    ['module' => 'Módulo 4 – Estruturação dos Marketplaces e Integração Bling', 'module_short' => 'M4', 'module_order' => 4, 'task_num' => '4.4', 'task_name' => 'Configuração do Mercado Envios e políticas de frete', 'responsible' => 'Time Marketplaces', 'duration' => 1, 'start_date' => '2026-08-05', 'end_date' => '2026-08-05', 'module_investment' => 1600.00],
    ['module' => 'Módulo 4 – Estruturação dos Marketplaces e Integração Bling', 'module_short' => 'M4', 'module_order' => 4, 'task_num' => '4.5', 'task_name' => 'Ativação e configuração do Mercado Ads', 'responsible' => 'Time Marketplaces', 'duration' => 1, 'start_date' => '2026-08-06', 'end_date' => '2026-08-06', 'module_investment' => 1600.00],
    ['module' => 'Módulo 4 – Estruturação dos Marketplaces e Integração Bling', 'module_short' => 'M4', 'module_order' => 4, 'task_num' => '4.6', 'task_name' => 'Integração Mercado Livre ↔ Bling (estoque, pedidos, NF-e)', 'responsible' => 'Time Marketplaces', 'duration' => 2, 'start_date' => '2026-08-07', 'end_date' => '2026-08-10', 'module_investment' => 1600.00],
    ['module' => 'Módulo 4 – Estruturação dos Marketplaces e Integração Bling', 'module_short' => 'M4', 'module_order' => 4, 'task_num' => '4.7', 'task_name' => 'Shopee: auditoria da conta existente', 'responsible' => 'Time Marketplaces', 'duration' => 1, 'start_date' => '2026-08-11', 'end_date' => '2026-08-11', 'module_investment' => 1600.00],
    ['module' => 'Módulo 4 – Estruturação dos Marketplaces e Integração Bling', 'module_short' => 'M4', 'module_order' => 4, 'task_num' => '4.8', 'task_name' => 'Otimização dos anúncios Shopee (ranqueamento)', 'responsible' => 'Time Marketplaces', 'duration' => 1, 'start_date' => '2026-08-12', 'end_date' => '2026-08-12', 'module_investment' => 1600.00],
    ['module' => 'Módulo 4 – Estruturação dos Marketplaces e Integração Bling', 'module_short' => 'M4', 'module_order' => 4, 'task_num' => '4.9', 'task_name' => 'Verificação e ajuste da integração Shopee ↔ Bling', 'responsible' => 'Time Marketplaces', 'duration' => 1, 'start_date' => '2026-08-13', 'end_date' => '2026-08-13', 'module_investment' => 1600.00],
    ['module' => 'Módulo 4 – Estruturação dos Marketplaces e Integração Bling', 'module_short' => 'M4', 'module_order' => 4, 'task_num' => '4.10', 'task_name' => 'Alinhamento do catálogo Shopee com estoque no Bling', 'responsible' => 'Time Marketplaces', 'duration' => 1, 'start_date' => '2026-08-14', 'end_date' => '2026-08-14', 'module_investment' => 1600.00],
    ['module' => 'Módulo 5 – Estruturação das Campanhas Pagas', 'module_short' => 'M5', 'module_order' => 5, 'task_num' => '5.1', 'task_name' => 'Criação e configuração da conta Google Ads (Shopping + Search)', 'responsible' => 'Time Mídia Paga', 'duration' => 2, 'start_date' => '2026-08-17', 'end_date' => '2026-08-18', 'module_investment' => 900.00],
    ['module' => 'Módulo 5 – Estruturação das Campanhas Pagas', 'module_short' => 'M5', 'module_order' => 5, 'task_num' => '5.2', 'task_name' => 'Configuração do Gerenciador de Negócios Meta Ads', 'responsible' => 'Time Mídia Paga', 'duration' => 1, 'start_date' => '2026-08-19', 'end_date' => '2026-08-19', 'module_investment' => 900.00],
    ['module' => 'Módulo 5 – Estruturação das Campanhas Pagas', 'module_short' => 'M5', 'module_order' => 5, 'task_num' => '5.3', 'task_name' => 'Estruturação das campanhas Meta Ads (topo, meio, fundo de funil)', 'responsible' => 'Time Mídia Paga', 'duration' => 3, 'start_date' => '2026-08-20', 'end_date' => '2026-08-24', 'module_investment' => 900.00],
    ['module' => 'Módulo 5 – Estruturação das Campanhas Pagas', 'module_short' => 'M5', 'module_order' => 5, 'task_num' => '5.4', 'task_name' => 'Definição de públicos, segmentações e criativos iniciais', 'responsible' => 'Time Mídia Paga', 'duration' => 2, 'start_date' => '2026-08-25', 'end_date' => '2026-08-26', 'module_investment' => 900.00],
    ['module' => 'Módulo 5 – Estruturação das Campanhas Pagas', 'module_short' => 'M5', 'module_order' => 5, 'task_num' => '5.5', 'task_name' => 'Configuração de conversões importadas do Bling (ROI real)', 'responsible' => 'Time Mídia Paga', 'duration' => 2, 'start_date' => '2026-08-27', 'end_date' => '2026-08-28', 'module_investment' => 900.00],
];
